name: plant_market

description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  intl: any
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  go_router: ^11.0.0
  flutter_localizations:
    sdk: flutter

  # http
  dio: ^5.3.3
  path: ^1.8.3
  dartz: ^0.10.1

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # local storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3

  # firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: any
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5

  # media
  assets_audio_player: ^3.1.1

  # UI
  like_button: ^2.0.5
  font_awesome_flutter: ^10.5.0
  salomon_bottom_bar: ^3.3.2
  timelines: ^0.1.0
  device_preview: ^1.1.0
  wave: ^0.2.2
  lottie: ^2.6.0
  shimmer: ^3.0.0
  pinput: ^3.0.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  injectable_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # true => generate multiple language => cannot run bunner command
  # false => can run bunner command =>  cannot generate
  generate: false
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lotties/
    - assets/audios/
    - assets/svg/
