name: plant_market

description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  intl: any
  flutter_dotenv: ^5.1.0
  flutter_email_sender: ^6.0.2
  after_layout: ^1.2.0
  go_router: ^11.0.0
  flutter_localizations:
    sdk: flutter

  # http
  dio: ^5.3.3
  path: ^1.8.3
  path_provider: ^2.1.1
  dartz: ^0.10.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  uuid: ^3.0.5
  url_launcher: ^6.2.1

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # local storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter:

  # firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: any
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5

  # media
  just_audio: ^0.9.35

  #device
  image_picker: ^1.0.4
  geolocator: ^10.1.0

  #animation
  flutter_animate: ^4.2.0+1
  flutter_staggered_animations: ^1.1.1
  sliver_tools: ^0.2.12

  # UI
  like_button: ^2.0.5
  font_awesome_flutter: ^10.5.0
  salomon_bottom_bar: ^3.3.2
  timelines: ^0.1.0
  device_preview: ^1.1.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  pinput: ^3.0.1
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.0

  # testing
  mockito: ^5.4.2

dev_dependencies:
  injectable_generator:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # true => generate multiple language => cannot run bunner command
  # false => can run bunner command =>  cannot generate
  generate: false
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lotties/
    - assets/svg/
