name: plant_market

description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  intl: any
  path: ^1.8.3
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  go_router: ^11.0.0
  dio: ^5.3.3
  flutter_localizations:
    sdk: flutter

  # firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: any
  firebase_storage: ^11.2.7
  json_annotation: ^4.8.1

dev_dependencies:
  injectable_generator:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: false
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
